#!/usr/bin/env bash
#
# Test code.

set -o errexit
set -o pipefail
set -o nounset

# Shell scripts
npm run format-sh-ci {**/*.sh,script/**}
npm run lint-sh {**/*.sh,script/**}

# Multiple formats
npm run format-code-ci ./**/*.{json,yml}
npm run format-code-ci ./**/*.md
npm run lint-md ./**/*.md
